<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance as Middleware;

class PreventRequestsDuringMaintenance extends Middleware
{
    /**
     * The URIs that should be reachable while maintenance mode is enabled.
     *
     * @var array<int, string>
     */
    protected $except = [
        //
    ];

    protected function hasValidBypassCookie($request, array $data = [])
    {
        return parent::hasValidBypassCookie($request, $data); // TODO: Change the autogenerated stub
    }
}
