CREATE TABLE account(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	role INT NULL,
	create_at DATE
);

CREATE TABLE user(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	role INT NULL,
	registed_at DATE,
	account_id INT NOT NULL
);

CREATE TABLE category(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL, 
	user_id INT NOT NULL
);

CREATE TABLE blog(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	content VARCHAR(255) NOT NULL,
	create_at DATE NOT NULL,
	category VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL
);

CREATE TABLE blog_category (
	blog_id INT NOT NULL,
	category_id INT NOT NULL
);

CREATE TABLE comment(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
	blog_id INT NOT NULL,
	reply_to INT,
	create_at INT NOT NULL
);

CREATE TABLE rate (
	user_id INT NOT NULL,
	blog_id INT NOT NULL,
	create_at DATE NOT NULL
);

CREATE TABLE vote (
	user_id INT NOT NULL,
	comment_id INT NOT NULL,
	create_at DATE
);